spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
logging:
  file: logs/bro_mall_server_dev.log
