package com.team.bromall.mapper;

import com.team.bromall.model.UserIntegrationConsumeSetting;
import com.team.bromall.model.UserIntegrationConsumeSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserIntegrationConsumeSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserIntegrationConsumeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserIntegrationConsumeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserIntegrationConsumeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserIntegrationConsumeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserIntegrationConsumeSetting> selectByExample(UserIntegrationConsumeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserIntegrationConsumeSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserIntegrationConsumeSetting record, @Param("example") UserIntegrationConsumeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserIntegrationConsumeSetting record, @Param("example") UserIntegrationConsumeSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserIntegrationConsumeSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserIntegrationConsumeSetting record);
}