package com.team.bromall.mapper;

import com.team.bromall.model.UserMemberRuleSetting;
import com.team.bromall.model.UserMemberRuleSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMemberRuleSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserMemberRuleSetting> selectByExample(UserMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserMemberRuleSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMemberRuleSetting record, @Param("example") UserMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserMemberRuleSetting record, @Param("example") UserMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_rule_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserMemberRuleSetting record);
}