package com.team.bromall.mapper;

import com.team.bromall.model.UserMember;
import com.team.bromall.model.UserMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserMember> selectByExample(UserMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMember record, @Param("example") UserMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserMember record, @Param("example") UserMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserMember record);
}