package com.team.bromall.mapper;

import com.team.bromall.model.UserMemberMemberTagRelation;
import com.team.bromall.model.UserMemberMemberTagRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMemberMemberTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserMemberMemberTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserMemberMemberTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserMemberMemberTagRelation> selectByExample(UserMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserMemberMemberTagRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMemberMemberTagRelation record, @Param("example") UserMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserMemberMemberTagRelation record, @Param("example") UserMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserMemberMemberTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_member_tag_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserMemberMemberTagRelation record);
}