package com.team.bromall.mapper;

import com.team.bromall.model.UserMemberStatisticsInfo;
import com.team.bromall.model.UserMemberStatisticsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMemberStatisticsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserMemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserMemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserMemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserMemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserMemberStatisticsInfo> selectByExample(UserMemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserMemberStatisticsInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMemberStatisticsInfo record, @Param("example") UserMemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserMemberStatisticsInfo record, @Param("example") UserMemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserMemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_statistics_info
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserMemberStatisticsInfo record);
}