package com.team.bromall.mapper;

import com.team.bromall.model.UserMemberLevel;
import com.team.bromall.model.UserMemberLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserMemberLevel> selectByExample(UserMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserMemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMemberLevel record, @Param("example") UserMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserMemberLevel record, @Param("example") UserMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_level
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserMemberLevel record);
}