package com.team.bromall.mapper;

import com.team.bromall.model.UserGrowthChangeHistory;
import com.team.bromall.model.UserGrowthChangeHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGrowthChangeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    long countByExample(UserGrowthChangeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByExample(UserGrowthChangeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insert(UserGrowthChangeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int insertSelective(UserGrowthChangeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    List<UserGrowthChangeHistory> selectByExample(UserGrowthChangeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    UserGrowthChangeHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserGrowthChangeHistory record, @Param("example") UserGrowthChangeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByExample(@Param("record") UserGrowthChangeHistory record, @Param("example") UserGrowthChangeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserGrowthChangeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_growth_change_history
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    int updateByPrimaryKey(UserGrowthChangeHistory record);
}