package com.team.bromall.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class PmsSkuStock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.product_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sku_code
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String skuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.low_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer lowStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp1
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String sp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp2
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String sp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp3
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String sp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.pic
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sale
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.promotion_price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private BigDecimal promotionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.lock_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer lockStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.id
     *
     * @return the value of pms_sku_stock.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.id
     *
     * @param id the value for pms_sku_stock.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.product_id
     *
     * @return the value of pms_sku_stock.product_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.product_id
     *
     * @param productId the value for pms_sku_stock.product_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sku_code
     *
     * @return the value of pms_sku_stock.sku_code
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sku_code
     *
     * @param skuCode the value for pms_sku_stock.sku_code
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.price
     *
     * @return the value of pms_sku_stock.price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.price
     *
     * @param price the value for pms_sku_stock.price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.stock
     *
     * @return the value of pms_sku_stock.stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.stock
     *
     * @param stock the value for pms_sku_stock.stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.low_stock
     *
     * @return the value of pms_sku_stock.low_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.low_stock
     *
     * @param lowStock the value for pms_sku_stock.low_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp1
     *
     * @return the value of pms_sku_stock.sp1
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getSp1() {
        return sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp1
     *
     * @param sp1 the value for pms_sku_stock.sp1
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setSp1(String sp1) {
        this.sp1 = sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp2
     *
     * @return the value of pms_sku_stock.sp2
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getSp2() {
        return sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp2
     *
     * @param sp2 the value for pms_sku_stock.sp2
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setSp2(String sp2) {
        this.sp2 = sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp3
     *
     * @return the value of pms_sku_stock.sp3
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getSp3() {
        return sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp3
     *
     * @param sp3 the value for pms_sku_stock.sp3
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setSp3(String sp3) {
        this.sp3 = sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.pic
     *
     * @return the value of pms_sku_stock.pic
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.pic
     *
     * @param pic the value for pms_sku_stock.pic
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sale
     *
     * @return the value of pms_sku_stock.sale
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sale
     *
     * @param sale the value for pms_sku_stock.sale
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.promotion_price
     *
     * @return the value of pms_sku_stock.promotion_price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.promotion_price
     *
     * @param promotionPrice the value for pms_sku_stock.promotion_price
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.lock_stock
     *
     * @return the value of pms_sku_stock.lock_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getLockStock() {
        return lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.lock_stock
     *
     * @param lockStock the value for pms_sku_stock.lock_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setLockStock(Integer lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", skuCode=").append(skuCode);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", lowStock=").append(lowStock);
        sb.append(", sp1=").append(sp1);
        sb.append(", sp2=").append(sp2);
        sb.append(", sp3=").append(sp3);
        sb.append(", pic=").append(pic);
        sb.append(", sale=").append(sale);
        sb.append(", promotionPrice=").append(promotionPrice);
        sb.append(", lockStock=").append(lockStock);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}