package com.team.bromall.model;

import java.io.Serializable;

public class UserIntegrationConsumeSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_integration_consume_setting.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer deductionPerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer maxPercentPerOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer useUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer couponStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_integration_consume_setting.id
     *
     * @return the value of user_integration_consume_setting.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_integration_consume_setting.id
     *
     * @param id the value for user_integration_consume_setting.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_integration_consume_setting.deduction_per_amount
     *
     * @return the value of user_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getDeductionPerAmount() {
        return deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_integration_consume_setting.deduction_per_amount
     *
     * @param deductionPerAmount the value for user_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setDeductionPerAmount(Integer deductionPerAmount) {
        this.deductionPerAmount = deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_integration_consume_setting.max_percent_per_order
     *
     * @return the value of user_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getMaxPercentPerOrder() {
        return maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_integration_consume_setting.max_percent_per_order
     *
     * @param maxPercentPerOrder the value for user_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setMaxPercentPerOrder(Integer maxPercentPerOrder) {
        this.maxPercentPerOrder = maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_integration_consume_setting.use_unit
     *
     * @return the value of user_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getUseUnit() {
        return useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_integration_consume_setting.use_unit
     *
     * @param useUnit the value for user_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setUseUnit(Integer useUnit) {
        this.useUnit = useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_integration_consume_setting.coupon_status
     *
     * @return the value of user_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_integration_consume_setting.coupon_status
     *
     * @param couponStatus the value for user_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setCouponStatus(Integer couponStatus) {
        this.couponStatus = couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integration_consume_setting
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deductionPerAmount=").append(deductionPerAmount);
        sb.append(", maxPercentPerOrder=").append(maxPercentPerOrder);
        sb.append(", useUnit=").append(useUnit);
        sb.append(", couponStatus=").append(couponStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}