package com.team.bromall.model;

import java.io.Serializable;
import java.util.Date;

public class UserMemberLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.member_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.create_time
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.ip
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.city
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.login_type
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Integer loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member_login_log.province
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_member_login_log
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.id
     *
     * @return the value of user_member_login_log.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.id
     *
     * @param id the value for user_member_login_log.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.member_id
     *
     * @return the value of user_member_login_log.member_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.member_id
     *
     * @param memberId the value for user_member_login_log.member_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.create_time
     *
     * @return the value of user_member_login_log.create_time
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.create_time
     *
     * @param createTime the value for user_member_login_log.create_time
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.ip
     *
     * @return the value of user_member_login_log.ip
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.ip
     *
     * @param ip the value for user_member_login_log.ip
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.city
     *
     * @return the value of user_member_login_log.city
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.city
     *
     * @param city the value for user_member_login_log.city
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.login_type
     *
     * @return the value of user_member_login_log.login_type
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.login_type
     *
     * @param loginType the value for user_member_login_log.login_type
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member_login_log.province
     *
     * @return the value of user_member_login_log.province
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member_login_log.province
     *
     * @param province the value for user_member_login_log.province
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member_login_log
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", createTime=").append(createTime);
        sb.append(", ip=").append(ip);
        sb.append(", city=").append(city);
        sb.append(", loginType=").append(loginType);
        sb.append(", province=").append(province);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}