package com.team.bromall.model;

import java.io.Serializable;

public class UserRolePermissionRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_permission_relation.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_permission_relation.role_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_permission_relation.permission_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role_permission_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_permission_relation.id
     *
     * @return the value of user_role_permission_relation.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_permission_relation.id
     *
     * @param id the value for user_role_permission_relation.id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_permission_relation.role_id
     *
     * @return the value of user_role_permission_relation.role_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_permission_relation.role_id
     *
     * @param roleId the value for user_role_permission_relation.role_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_permission_relation.permission_id
     *
     * @return the value of user_role_permission_relation.permission_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_permission_relation.permission_id
     *
     * @param permissionId the value for user_role_permission_relation.permission_id
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_permission_relation
     *
     * @mbg.generated Fri Nov 29 11:29:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}